kind: pipeline
name: default

workspace:
  path: /home/node/app

steps:
  - name: build
    image: node:14.21.3
    volumes:
      - name: yarncache
        path: /usr/local/share/.cache/yarn
    commands:
      - yarn --registry=https://registry.yarnpkg.com
      - yarn build
    environment:
      CI: false
      GENERATE_SOURCEMAP: false
      COS_SECRET_ID:
        from_secret: COS_SECRET_ID
      COS_SECRET_KEY:
        from_secret: COS_SECRET_KEY

  - name: deploy
    image: ubuntu:22.04
    volumes:
      - name: webroot
        path: /webroot
    commands:
      - mkdir -p /webroot/paperplane-app/
      - rm -rf /webroot/paperplane-app/*
      - cp -rf ./dist/* /webroot/paperplane-app/

volumes:
  - name: webroot
    host:
      path: /root/www
  - name: yarncache
    host:
      path: /root/.yarncache

trigger:
  branch:
    - master
